baseurl = "https://songfei1983.github.io"
languageCode = "en-us"
paginate = 10
publishDir = "docs"
theme = "hello-friend-ng"
title = "Fei Blog"

[params]
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
dateformShort = "Jan 2"

# Subtitle for home
homeSubtitle = "Software Developer"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you linke
enableSharingButtons = true

# Metadata mostly used in document's head
description = "fei blog"
images = [""]
keywords = "fei, blog"

# Default theme "light" or "dark"
defaultTheme = "dark"

[taxonomies]
category = "blog"
series = "series"
tag = "tags"

[languages]
[languages.en]
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
keywords = "fei, blog"
readOtherPosts = "Read other posts"
subtitle = "Software Engineer"
title = "Song Fei"

[languages.en.params.logo]
logoHomeLink = "/"
logoText = "cd /top"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
